// Ui options
export const UI_HAMBURGER_CLICKED = 'HAMBURGER_CLICKED'
export const UI_REGISTER_CLICKED = 'REGISTER_CLICKED'
export const UI_LOGIN_BACK_CLICKED = 'LOGIN_BACK'

//Profile
export const PROFILE_CLICKED = 'PROFILE_CLICKED'
export const PROFILE_OUT = 'PROFILE_OUT'
export const PROFILE_SIGN_UP =  'PROFILE_SIGN_UP'
export const PROFILE_AUTH = 'PROFILE_AUTH'

//CHANGE HANDLER PROFILE
export const PROFILE_CHANGE_FIRSTNAME = 'PROFILE_CHANGE_FIRSTNAME'
export const PROFILE_CHANGE_LASTNAME ='PROFILE_CHANGE_LASTNAME'
export const PROFILE_CHANGE_COUNTRY ='PROFILE_CHANGE_COUNTRY'
export const PROFILE_CHANGE_CITY ='PROFILE_CHANGE_CITY'
export const PROFILE_CHANGE_BLOODTYPE ='PROFILE_CHANGE_BLOODTYPE'
export const PROFILE_CHANGE_STATUS ='PROFILE_CHANGE_STATUS'
export const PROFILE_CHANGE_ACTION = 'PROFILE_CHANGE_ACTION'
export const PROFILE_CHANGE_ILLNESS ='PROFILE_CHANGE_ILLNESS'
export const PROFILE_CHANGE_DESCRIPTION ='PROFILE_CHANGE_DESCRIPTION'
export const PROFILE_CHANGE_PHONENUMBER ='PROFILE_CHANGE_PHONENUMBER'
export const PROFILE_CHANGE_BIRTHDATE ='PROFILE_CHANGE_BIRTHDATE'
export const PROFILE_CHANGE_GENDER ='PROFILE_CHANGE_GENDER'
export const PROFILE_CHANGE_BLOOD_RECEIVE_START ='PROFILE_CHANGE_BLOOD_RECEIVE_START'
export const PROFILE_CHANGE_BLOOD_RECEIVE_END ='PROFILE_CHANGE_BLOOD_RECEIVE_END'
export const PROFILE_CHANGE_LINK_FACEBOOK ='PROFILE_CHANGE_LINK_FACEBOOK'
export const PROFILE_CHANGE_LINK_TWITTER ='PROFILE_CHANGE_LINK_TWITTER'
export const PROFILE_CHANGE_LINK_INSTAGRAM ='PROFILE_CHANGE_LINK_INSTAGRAM'
export const PROFILE_CHANGE_LINK_LINKEDIN ='PROFILE_CHANGE_LINK_LINKEDIN'
export const PROFILE_CHANGE_LINK_GOOGLE ='PROFILE_CHANGE_LINK_GOOGLE'

// CHANGE HANDLER EMAIL PASSWORD
export const AUTH_CHANGE_EMAIL = 'AUTH_CHANGE_EMAIL'
export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORDS'


//Auth
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_REGISTER  = 'AUTH_REGISTER'


// Blood Receiving Table
export const BLOOD_RECEIVING_TABLE_LOAD = 'BLOOD_RECEIVING_TABLE_LOAD'
export const BLOOD_RECEIVING_TABLE_LOAD_SUCCESS = 'BLOOD_RECEIVING_TABLE_LOAD_SUCCESS'
export const BLOOD_RECEIVING_TABLE_LOAD_FAIL = 'BLOOD_RECEIVING_TABLE_LOAD_FAIL'
export const BLOOD_RECEIVING_TABLE_LOAD_DROPDOWN = 'BLOOD_RECEIVING_AVAIL_BLOOD_LOAD'
export const BLOOD_RECEIVING_TABLE_CHANGE_DROPDOWN = 'BLOOD_RECEIVING_TABLE_CHANGE_DROPDOWN'
export const BLOOD_RECEIVING_TABLE_LOADING = 'BLOOD_RECEIVING_TABLE_LOADING'

// Blood Donor Table
export const BLOOD_DONOR_TABLE_LOAD = 'BLOOD_DONOR_TABLE_LOAD'
export const BLOOD_DONOR_TABLE_LOAD_SUCCESS = 'BLOOD_DONOR_TABLE_LOAD_SUCCESS'
export const BLOOD_DONOR_TABLE_LOAD_FAIL = 'BLOOD_DONOR_TABLE_LOAD_FAIL'
export const BLOOD_DONOR_TABLE_LOAD_DROPDOWN = 'BLOOD_DONOR_TABLE_LOAD_DROPDOWN'
export const BLOOD_DONOR_TABLE_CHANGE_DROPDOWN = 'BLOOD_DONOT_TABLE_CHANGE_DROPDOWN'
export const BLOOD_DONOR_TABLE_LOADING = 'BLOOD_DONOR_TABLE_LOADING'